# Generated by Django 5.0.6 on 2024-06-20 02:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field='height', null=True, upload_to='photos/', width_field='width')),
                ('height', models.PositiveIntegerField(default=5)),
                ('width', models.PositiveIntegerField(default=5)),
                ('phone', models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='The phone must be 20 numbers long.', regex='^\\d{20}$')])),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField(help_text='The age must be between 18 and 100 years.', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
