# Generated by Django 5.0.6 on 2024-06-20 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='The phone must be 10 numbers long.', regex='^\\d{10}$')]),
        ),
    ]
