# Generated by Django 5.0.6 on 2024-06-20 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='width',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(help_text='The age must be between 18 and 100 years.', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, height_field=5, null=True, upload_to='photos/', width_field=5),
        ),
    ]
