# Generated by Django 5.0.6 on 2024-06-20 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_height_remove_profile_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(help_text='The age must be between 18 and 100 years.', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='photos/', width_field='width'),
        ),
    ]
