# Generated by Django 5.0.6 on 2024-06-20 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_address_alter_profile_age_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=19, help_text='The age must be between 18 and 100 years.', validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
