# Generated by Django 5.0.6 on 2024-06-20 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('professor', '0002_professor_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='personal_number',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.AddField(
            model_name='professor',
            name='profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
